#!/bin/bash
# This hook is sourced before this virtualenv is deactivated.

if [[ -n $OLD_PATH ]]; then
    export PATH=$OLD_PATH
    unset OLD_PATH
fi

if [[ -n $LD_LIBRARY_PATH ]]; then
    export LD_LIBRARY_PATH=$OLD_LD_LIBRARY_PATH
    unset OLD_LD_LIBRARY_PATH
fi

unset PROV_HOME="$HOME/work/provision"
unalias cdsrc
unalias cdbin
unalias cdconf
unalias cdlog
unalias cdlib
unalias cdtest
